### PR TITLE
Pulling in v0.21 and passing $request to handle_request

### PR DESCRIPTION
**Pull request by deckerrj**
Initially a pull request based on v0.21. Added functionality for passing $request to the handle_request method. This is due to my work with an HTML templating engine that does internal forking for long-running page requests. In order to serve this over FCGI I need the original $request object to Detach/Attach as appropriate. This lets me do so in the handle_request method.

### CODE REVIEW

**Comment by deckerrj** [comment]
Still waiting on this pull request. Is there anything I can do to make this easier to pull Stevan?

**Comment by stevan** [comment]
@deckerrj I have not been releasing this module lately, it has mostly been @botfish, however if he is not available to do that I can try and make some time to get it up. Alternatively I could give you comaint on CPAN if you are interested in that.

**Comment by deckerrj** [comment]
@bobtfish passed me upstream to you. I'm happy to take up comaint on CPAN, but don't have a lot of prior experience contributing to CPAN.

**Comment by stevan** [comment]
Haha, okay then, I will try get you comaint tonight when I get home from work.

**Comment by stevan** [comment]
@deckerrj the latest release should be up on CPAN shortly. I can still give you comaint if you like, just send me your PAUSE username and I will add you.

**Comment by stevan** [comment]
@deckerrj And I perhaps spoke too soon, it appears that @bobtfish owns some of the files in the distro so CPAN will mark it as "unauthorized" for now until @bobtfish fixes this.

**Comment by deckerrj** [comment]
@stevan My PAUSE userid is DECKERRJ.

**Comment by bobtfish** [comment]
All fixed now!

**Pull request merged**
